### ISSUE TITLE
Activity Group Update

### ISSUE THREAD

**Issue by SmokyBob** [GoogleDeveloperExperts/experts-app-backend#11]
The current Technology activity tags should fall under the following larger 4 categories:

Content: #blogpost,#video,#article,#tutorial,#forumpost,
# techdocs,#book,#translation,#opensourcecode

Speaking: #techtalk 

Testing: #bugreport

Pack Leader: #interview, #community

Update the PG AT AG Master List with the required changes
# gdeProgram renamed to #expertsProgram

**Comment by patt0** [comment]
I am not entirely convinced that we need to use these 4 groups for the app,
front or back, these are more of an internal classification that is being
used by the program group.

The Activity Group was really a method of capturing meta data about the
activities, so we should really try to understand is that is procuring any
value at all to the program?

When I look at the way that the team works, and the reports that they are
really trying to extract, I see none of that data, perhaps because its non
existent for most posts.

Patrick Martinent

**Comment by SmokyBob** [comment]
I understand your point.
I think that the main cause for metadata being missing on most activities, is due to the frontend making metadata input really slow.
Hopefully the new site should be more accessible/usable and faster to jump on the different activities.

I think we could ask in the next meeting if we want to keep tracking metadata in the current format or something different (less fields kind of more descriptive? and almost the same for all the AGs so that they can be aggregated in the reports?)

**Comment by SmokyBob** [comment]
Discussed this point with Nat and Marie today in the Hangout; Activity Groups are fine as are currently implemented.
Closing the issue
